# Generated by Django 5.2.11 on 2026-02-23 12:03

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('cpf', models.CharField(db_index=True, help_text='Somente números (11 dígitos).', max_length=11, unique=True, validators=[accounts.models.validate_cpf])),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('street', models.CharField(blank=True, default='', max_length=200)),
                ('number', models.CharField(blank=True, default='', max_length=20)),
                ('complement', models.CharField(blank=True, default='', max_length=120)),
                ('neighborhood', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cpf'], name='accounts_ac_cpf_3098f8_idx'), models.Index(fields=['created_at'], name='accounts_ac_created_2e62af_idx')],
            },
        ),
    ]
