# Generated by Django 5.2.11 on 2026-02-24 17:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='cpf',
            field=models.CharField(db_index=True, help_text='Somente números (11 dígitos).', max_length=14, unique=True, validators=[accounts.models.validate_cpf]),
        ),
    ]
