# Generated by Django 5.2.11 on 2026-03-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountprofile_pix_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='pix_key_type',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('phone', 'Celular'), ('email', 'Email'), ('random', 'Chave Aleatória')], default='', max_length=10),
        ),
    ]
