# Generated by Django 5.2.11 on 2026-03-11 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_name', models.CharField(blank=True, max_length=120)),
                ('referred_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo')], default='PENDING', max_length=12)),
                ('credits_cents', models.PositiveIntegerField(default=0)),
                ('commission_eligible', models.BooleanField(default=False)),
                ('referral_level', models.PositiveSmallIntegerField(default=1)),
                ('referral_code_used', models.CharField(blank=True, max_length=24)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('referred_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_invite_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('percent_bp', models.PositiveSmallIntegerField()),
                ('amount_cents', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions', to=settings.AUTH_USER_MODEL)),
                ('source_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions', to='portfolio.investment')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_referral_commissions', to=settings.AUTH_USER_MODEL)),
                ('source_invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_generated', to='referrals.referralinvite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='referralinvite',
            index=models.Index(fields=['referrer', 'status'], name='referrals_r_referre_73df9f_idx'),
        ),
        migrations.AddIndex(
            model_name='referralinvite',
            index=models.Index(fields=['referrer', 'status', 'commission_eligible'], name='referrals_r_referre_6314ae_idx'),
        ),
        migrations.AddIndex(
            model_name='referralinvite',
            index=models.Index(fields=['status'], name='referrals_r_status_441de7_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralinvite',
            constraint=models.CheckConstraint(condition=models.Q(('referrer', models.F('referred_user')), _negated=True), name='referral_referrer_diff_referred'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['beneficiary', 'created_at'], name='referrals_r_benefic_10c826_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['source_user', 'created_at'], name='referrals_r_source__3ed71a_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralcommission',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 3)), name='referral_commission_level_1_3'),
        ),
        migrations.AddConstraint(
            model_name='referralcommission',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='referral_commission_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='referralcommission',
            constraint=models.UniqueConstraint(fields=('source_investment', 'beneficiary'), name='uniq_referral_commission_investment_beneficiary'),
        ),
    ]
