# Generated by Django 5.2.11 on 2026-02-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referralinvite',
            new_name='referrals_r_referre_73df9f_idx',
            old_name='referrals_r_referr_f17f46_idx',
        ),
        migrations.RenameIndex(
            model_name='referralinvite',
            new_name='referrals_r_status_441de7_idx',
            old_name='referrals_r_status_21db53_idx',
        ),
    ]
