# Generated by Django 5.2.11 on 2026-02-20 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultLedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount_cents", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("external_ref", models.CharField(blank=True, max_length=80, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_result_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user", "created_at"], name="withdrawals__user_id_63de77_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=~models.Q(amount_cents=0),
                        name="result_ledger_amount_non_zero",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "withdrawal_type",
                    models.CharField(
                        choices=[
                            ("RESULT_SETTLEMENT", "Liquidacao de resultado"),
                            ("CAPITAL_REDEMPTION", "Resgate de capital"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                ("pix_key", models.CharField(blank=True, max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("APPROVED", "Aprovado"),
                            ("REJECTED", "Rejeitado"),
                            ("PAID", "Pago"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("admin_note", models.TextField(blank=True)),
                ("external_ref", models.CharField(blank=True, max_length=80, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="withdrawals__user_id_492a7c_idx"),
                    models.Index(
                        fields=["user", "withdrawal_type", "status"],
                        name="withdrawals__user_id_35ea9e_idx",
                    ),
                    models.Index(fields=["status"], name="withdrawals__status_8b0179_idx"),
                ],
            },
        ),
    ]
