# Generated by Django 5.2.11 on 2026-03-03 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPerformanceDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField()),
                ('performance_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('base_capital_cents', models.PositiveIntegerField()),
                ('result_cents', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reference_date', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='resultledgerentry',
            new_name='withdrawals_user_id_cc72f3_idx',
            old_name='withdrawals__user_id_63de77_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='withdrawals_user_id_93f65e_idx',
            old_name='withdrawals__user_id_492a7c_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='withdrawals_user_id_897ba0_idx',
            old_name='withdrawals__user_id_35ea9e_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='withdrawals_status_00b1c5_idx',
            old_name='withdrawals__status_8b0179_idx',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='scheduled_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'withdrawal_type', 'scheduled_for'], name='withdrawals_user_id_7b619a_idx'),
        ),
        migrations.AddField(
            model_name='dailyperformancedistribution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_performance_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyperformancedistribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyperformancedistribution',
            index=models.Index(fields=['reference_date'], name='withdrawals_referen_e17c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyperformancedistribution',
            index=models.Index(fields=['user', 'reference_date'], name='withdrawals_user_id_9645fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyperformancedistribution',
            constraint=models.UniqueConstraint(fields=('user', 'reference_date'), name='uniq_daily_performance_per_user_date'),
        ),
    ]
