# Generated by Django 5.2.11 on 2026-02-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("withdrawals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="scheduled_for",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["user", "withdrawal_type", "scheduled_for"],
                name="withdrawals__user_id_56a220_idx",
            ),
        ),
    ]
