# Generated by Django 5.2.11 on 2026-02-20 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("withdrawals", "0002_withdrawalrequest_scheduled_for_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPerformanceDistribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference_date", models.DateField()),
                ("performance_percent", models.DecimalField(decimal_places=4, max_digits=7)),
                ("base_capital_cents", models.PositiveIntegerField()),
                ("result_cents", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_daily_performance_distributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_performance_distributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reference_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dailyperformancedistribution",
            index=models.Index(fields=["reference_date"], name="withdrawals__referen_1180ba_idx"),
        ),
        migrations.AddIndex(
            model_name="dailyperformancedistribution",
            index=models.Index(fields=["user", "reference_date"], name="withdrawals__user_id_8b29fb_idx"),
        ),
        migrations.AddConstraint(
            model_name="dailyperformancedistribution",
            constraint=models.UniqueConstraint(
                fields=("user", "reference_date"),
                name="uniq_daily_performance_per_user_date",
            ),
        ),
    ]
