# Generated by Django 5.2.11 on 2026-02-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0003_dailyperformancedistribution'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyperformancedistribution',
            new_name='withdrawals_referen_e17c7e_idx',
            old_name='withdrawals__referen_1180ba_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyperformancedistribution',
            new_name='withdrawals_user_id_9645fc_idx',
            old_name='withdrawals__user_id_8b29fb_idx',
        ),
        migrations.RenameIndex(
            model_name='resultledgerentry',
            new_name='withdrawals_user_id_cc72f3_idx',
            old_name='withdrawals__user_id_63de77_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='withdrawals_user_id_93f65e_idx',
            old_name='withdrawals__user_id_492a7c_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='withdrawals_user_id_897ba0_idx',
            old_name='withdrawals__user_id_35ea9e_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='withdrawals_user_id_7b619a_idx',
            old_name='withdrawals__user_id_56a220_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='withdrawals_status_00b1c5_idx',
            old_name='withdrawals__status_8b0179_idx',
        ),
    ]
