# Generated by Django 5.2.11 on 2026-02-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_8a7c6b_idx',
            old_name='notificatio_user_id_30754f_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_c62b26_idx',
            old_name='notificatio_user_id_f71c56_idx',
        ),
    ]
